"""Writes crates/xtts/src/text_tables.rs from coqui-tts' XTTS tokenizer tables
(abbreviations, symbols, character limits).

    python scripts/gen_text_tables.py > crates/xtts/src/text_tables.rs
"""
from TTS.tts.layers.xtts import tokenizer as t

def rs(s):
    return "r#\"" + s + "\"#"

out = ["//! Generated by scripts/gen_text_tables.py from coqui-tts' XTTS tokenizer.",
       "//! Do not edit by hand.", "", "#![allow(clippy::all)]", ""]

def table(name, d):
    out.append(f"pub const {name}: &[(&str, &[(&str, &str)])] = &[")
    for lang, pairs in d.items():
        out.append(f"    (\"{lang}\", &[")
        for rx, rep in pairs:
            out.append(f"        ({rs(rx.pattern)}, {rs(rep)}),")
        out.append("    ]),")
    out.append("];")
    out.append("")

table("ABBREVIATIONS", t._abbreviations)
table("SYMBOLS", t._symbols_multilingual)
tok = t.VoiceBpeTokenizer()
out.append("pub const CHAR_LIMITS: &[(&str, usize)] = &[")
for lang, n in tok.char_limits.items():
    out.append(f"    (\"{lang}\", {n}),")
out.append("];")
print("\n".join(out))
